### ISSUE TITLE
ListItem's avatar uri not working

### ISSUE THREAD

**Issue by webraptor** [react-native-training/react-native-elements#444]
### Description
Upgraded from RNE 0.12.2 to RNE 0.13
## Expected
Expected the images used as avatar within the listItem elements to remain the same
## Actually
The images used as avatar within the listItem elements have sizing issues which destroys entire listItem's styling
Visual aids over here: https://github.com/react-native-training/react-native-elements/commit/ae9db39f745955ee09e8581fdf135bd831e9b7c8#commitcomment-22699038

### Reproduction Steps

Style and set width / height of the avatar element in a listItem , using RNE 0.12.2 
Upgrade to RNE 0.13 and see the changes.

### Issue triggered by

Commit [#7bc2e6f](https://github.com/react-native-training/react-native-elements/commit/7bc2e6f5f0874254b4c56fa27b9f61c3f699fc57)

### Solution
Since Avatar component has containerStyle, avatarStyle, overlayContainerStyle maybe it is best to expose all 3 within listItem.

**Comment by roadev** [comment]
+1
Same issue here!

**Comment by xavier-villelegier** [comment]
Hey @webraptor ,

I think it's more likely because of https://github.com/react-native-training/react-native-elements/commit/7bc2e6f5f0874254b4c56fa27b9f61c3f699fc57, because the `avatarStyle` is not passed to the `avatarStyle` of the Avatar component but to the `containerStyle`. (And this PR was not merged before 12.2 too.)

Does it work if you set your RNE version in your `package.json` to:
```
"react-native-elements": "git://github.com/react-native-training/react-native-elements.git#331e194"
```
(This was the commit just before the merge)

If it was working at this commit, can you give me a sample of code to clearly reproduce this issue, to be able to fix that properly ?

**Comment by webraptor** [comment]
I'm out of the office. I'll be able to check it out on Monday only.

**Comment by webraptor** [comment]
@xavier-villelegier Yeap, just tested with both #331e194 and #7bc2e6f and I can confirm that #7bc2e6f is the one that introduces the issue.

**Comment by xavier-villelegier** [comment]
Yep that's what I was planning. However, I still think that the `ListItem` tries to handle too many things on its own, and I don't know if exposing the entire `Avatar` API through the `ListItem` is a good thing...
I'll open a PR to fix that because it's clearly a regression, thank's for your help @webraptor !

**Comment by yash2code** [comment]
same issue . Is it resolved or is there any alternative ?

**Comment by xavier-villelegier** [comment]
@yash2code The fix has been merged and should be in the next release.
The alternative for now is to use a custom Avatar component
```js
<ListItem avatar={<Avatar avatarStyle={yourStyle} />} />
```

**Comment by Monte9** [comment]
@yash2code just release `v0.14.0`. It should have a fix on it. Please report back if this is still an issue.

**Comment by yash2code** [comment]
@Monte9  not working

**Comment by webraptor** [comment]
The fix has introduced new props. avatarstyle remains but I think avatarContainerStyle was added

**Comment by yash2code** [comment]
@Monte9  @webraptor  I rechecked the docs. I am still not able to increase the size of avatar . Tried avatarStyle avatarContainerStyle avatarOverlayContainerStyle . Styling for containers works but that doesn't affect the avatar . 




avatarContainerStyle | none | object (style) | Avatar outer container styling (optional)
avatarOverlayContainerStyle






avatarContainerStyle | none | object (style) | Avatar outer container styling (optional)
avatarOverlayContainerStyle

**Comment by xavier-villelegier** [comment]
@yash2code Can you give me a sample of a `ListItem` using `avatarStyle` that was working before in order to be able to have an example of what it was supposed to do ?

**Comment by yash2code** [comment]
@xavier-villelegier  This is my code and being clear that `avatarStyle` was not working before too :

```javascript

<ListItem
                      badge={{ value: 3, badgeTextStyle: { color: 'red' }, badgeContainerStyle: { marginTop: 10, color:'orange' } }}
                      roundAvatar
                      title={`${item.name.first} ${item.name.last}`}
                      subtitle={item.email}
                      avatar={{ uri: item.picture.thumbnail }}
                     avatarStyle={{borderRadius:50, height:100, width:100 }}
                      containerStyle={{borderBottomWidth: 0, padding:0 }}
                    />
```

**Comment by xavier-villelegier** [comment]
Oh okay I though it was working ! So @webraptor what do you mean by "can no longer be set" in the issue title ? You said that it was working for you before the merge of https://github.com/react-native-training/react-native-elements/commit/7bc2e6f5f0874254b4c56fa27b9f61c3f699fc57, can you give us an example of how you made it work ?

**Comment by webraptor** [comment]
We previously had below styling applied to _avatarStyle_. Now it is applied to _avatarContainerStyle_

`{
    width: 60,
    height: 60,
    backgroundColor: theme.colors.deltaMedium,
    borderRadius: 30,
    overflow: 'hidden'
  },`

**Comment by yash2code** [comment]
@webraptor As i have mentioned , `avatarContainerStyle`  is not working for avatar though the background of avatar is  affected.

**Comment by webraptor** [comment]
I don't know what to say then. Must be some sort of conflict or issue between your outer wrapping elements and how avatar component is constructed. Did you look into the source of the avatar component to understand how it is built?

**Comment by yash2code** [comment]
@webraptor  fetching avatar uri from [randomuser.me](https://randomuser.me)

**Comment by webraptor** [comment]
@yash2code I don't see how that's rrelevant to the problem at hand.

**Comment by yash2code** [comment]
@webraptor  exactly, here 's the code: 

```javascript

makeRemoteRequest = () => {
    const { page, seed } = this.state;
    const url = `https://randomuser.me/api/?seed=${seed}&page=${page}&results=10`;
    this.setState({ loading: true });
    fetch(url)
      .then(res => res.json())
      .then(res => {
        this.setState({
          data: page === 1 ? res.results : [...this.state.data, ...res.results],
          filteredUsers: page === 1 ? res.results : [...this.state.data, ...res.results],
          error: res.error || null,
          loading: false,
          refreshing: false
        });
      })
      .catch(error => {
        this.setState({ error, loading: false });
      });
  };
renderList(item, i) {
    
         

        return (<Animated.View 
                
                style={[{ zIndex: 5 }]}>
                
                
       <Card 
                    containerStyle={{borderColor: 'transparent'}}>

                    <ListItem
                      badge={{ value: 3, badgeTextStyle: { color: 'red' }, badgeContainerStyle: { marginTop: 10, color:'orange' } }}
                      roundAvatar
                      title={`${item.name.first} ${item.name.last}`}
                      subtitle={item.email}
                      avatar={{ uri: item.picture.thumbnail }}
                     avatarStyle={{borderRadius:50, height:100, width:100 }}
                      containerStyle={{borderBottomWidth: 0, padding:0 }}
                    />
                   
      </Card>
             
              
            </Animated.View> 



          )

        
  }

  render() {

    if (!this.state.isReady) {
      return <AppLoading />;
    }

    return (
     
         <List
         containerStyle={{ borderTopWidth: 0, borderBottomWidth: 0 }}>
     
      <FlatList
         data={this.state.filteredUsers}
         keyExtractor={item => item.email}
         ListHeaderComponent={this.renderHeader()}
         renderItem={({item, index}) => this.renderList(item ,index)}
        
      />
    </List>
    
    );
  }

```

**Comment by webraptor** [comment]
`avatarStyle={{borderRadius:50, height:100, width:100 }} `
should be 
`avatarContainerStyle={{borderRadius:50, height:100, width:100 }}`

This is how listItem constructs the avatar section:
`
<View style={styles.avatar}>
  {React.isValidElement(avatar)
    ? avatar
    : <Avatar
        avatarStyle={avatarStyle && avatarStyle}
        containerStyle={avatarContainerStyle && avatarContainerStyle}
        overlayContainerStyle={
          avatarOverlayContainerStyle && avatarOverlayContainerStyle
        }
        rounded={roundAvatar}
        source={avatar}
      />}
</View>}`

**Comment by yash2code** [comment]
@webraptor  already tried i have mentioned above :(

**Comment by webraptor** [comment]
In that case, just like I said before, it's probably due to some construction / styling conflicts you have on your side of the code. You should use the inspector to track down the issue.

**Comment by yash2code** [comment]
@webraptor the code above is all that have styling

**Comment by webraptor** [comment]
Try replacing
`avatar={{ uri: item.picture.thumbnail }} avatarStyle={{borderRadius:50, height:100, width:100 }}`
with
`
avatar={<Image source={{ uri: item.picture.thumbnail }} style={{borderRadius:50, height:100, width:100 }} />}
`
and see what happens

**Comment by yash2code** [comment]
@webraptor cool and tnx , it worked . Still I think package or docs  should be fixed. tnx again :)

**Comment by xavier-villelegier** [comment]
@yash2code @webraptor I'm just curious to know if using `width` and `height` props of the `Avatar` would have worked ?
```js
<ListItem
  avatar={<Avatar width={100} height={100} />}
/>
```

**Comment by webraptor** [comment]
@xavier-villelegier I think so because you're also using the _Avatar_ component directly, just like I mentioned direct _Image_ usage earlier. The problem was only affecting those using image source for the avatar property of the listItem.

**Comment by Monte9** [comment]
@webraptor thanks for helping debug this issue. 

There still seems to be a issue with not being able to use the `uri` on the avatar prop for the ListItem. Reopening this issue in case anyone wants to submit a PR for this.

**Comment by iRoachie** [comment]
Hey @Monte9 I couldn't reproduce this on Snack or locally. Is it `avatar={{ uri: l.avatar_url }}` on the `ListItem`.

If so here's a snack with it working as expected. https://snack.expo.io/BJsr5MsSb

**Comment by yash2code** [comment]
@iRoachie remove the Stylesheet , its working 
![asd](https://user-images.githubusercontent.com/20199248/28302717-b5d3cc12-6bac-11e7-9a30-22da68afadfd.PNG)

**Comment by iRoachie** [comment]
Seems to be resolved then. Feel free to reopen if the problem pops up again.

**Comment by MrHubble** [comment]
@webraptor @xavier-villelegier thanks for all of your helpful input on this.

I experienced this issue after upgrading from 0.12.2 to 0.16.0. Example:

<img width="283" alt="screen shot 2017-09-15 at 6 45 43 pm" src="https://user-images.githubusercontent.com/2251631/30474988-b0089298-9a48-11e7-8009-f58e078e5800.png">

Changing from `avatarStyle` to `avatarContainerStyle` didn't work for me either. However, your other suggestion did work for me:

````js
avatar={<Image source={require('../assets/images/truck.png')} 
style={{ height: 30, width: 60 }} />}
````

I also had to add some styling to the title so my avatar didn't overlap it:
````js
titleStyle={{ marginLeft: 100 }}
````

Thanks again!

**Comment by ToBiMaR** [comment]
I found that directly using the image name within the avatar tag, like the above requires, would show the image. However, trying to make use of 'l.avatar_url' as the uri would not work if the avatar_url comes from the assets folder. However, change the avatar from the assets folder to that of an http/https address and then the avatar shows.

```avatar_url: 'https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg',```

```avatar={{uri: l.avatar_url}}```

Is there a specific reason as to why this is?

**Comment by xavier-villelegier** [comment]
@ToBiMaR This is the default React Native `Image` component behavior, have a look [at the documentation](https://facebook.github.io/react-native/docs/image.html)

**Comment by presencewebdesign** [comment]
In my ListItem avatar I can't set the background colour to the same as the foreground? 
I am loading a PNG image as the avatar, the background is not transparent, does anyone know how to change this?

In the 0.19.1 version you used to be able to do 
avatarOverlayContainerStyle={{width: 24, height: 24, backgroundColor: '#2b7abf'}}

![image](https://user-images.githubusercontent.com/28238014/66198494-74c31100-e694-11e9-819f-41b21e4344aa.png)

**Comment by iRoachie** [comment]
@presencewebdesign It's `overlayContainerStyle` now
