### ISSUE TITLE
SearchBar icons do not center (not responsive)

### ISSUE THREAD

**Issue by peacechen** [react-native-training/react-native-elements#537]
### Description

The icons in the SearchBar component do not center vertically with different heights.  Automatic centering is required to support various device resolutions.  Upon inspection, the icons are positioned absolutely with static offsets which is a problem.

RNE 0.15

### Reproduction Steps and Sample Code

```
<SearchBar
	placeholder='Search things'
	placeholderTextColor={'#ccc'}
	onChangeText={this.myFilter}
	containerStyle={[styles.searchContainer]}
	inputStyle={[s.ma1, s.pl4, s.black, s.f4, {height: sizes.h2}]}
	lightTheme={true}
	round={true}
	icon={{ color: '#999', name: 'search' }}
	clearIcon={{ color: '#999', name: 'close' }}
/>
```

I'm using react-native-tachyons for responsive sizing.  The above looks good on iPad, but the icons are way off on iPhone.

### Solution

I initially started a PR, but the design of SearchBar is too broken to support responsive design.  Instead of reinventing the wheel, I found [react-native-material-design-searchbar](https://github.com/ananddayalan/react-native-material-design-searchbar) to be well designed, including responsiveness.  Recommend using that and wrapping it to be backwards compatible with existing props.

**Comment by Monte9** [comment]
@peacechen thanks for the issue & posting a potential solution. 

I agree that the SearchBar could be improved. In fact, I am working on a rewrite of the `SearchBar` component for the RNE 1.0 release. If you have any suggests on how the SearchBar components can be improved let me know.

**Comment by peacechen** [comment]
I'm a proponent of DRY (don't repeat yourself), and since there's a good search bar library why not leverage it.  Perhaps if you just want the experience of writing one from scratch, that's your call but it'll be a time investment to get it right.  Creating a responsive component is top priority to me.

**Comment by iRoachie** [comment]
When @xavier-villelegier updates the default searchbar this should be fixed. Will leave It open till then

**Comment by xavier-villelegier** [comment]
@chetanparakh Please refer to the labels to know the state of the issues.

* WIP: Still work in progress
* Fixed - Next Release: The issue has been fixed and will be available in the next release

by the way this is not a critical bug as you can still use
`icon={{ name: 'search', style: { marginTop: 8 } }}` to apply a margin on the Icon.

**Comment by peacechen** [comment]
It's been 8 months and still no progress.  I'm surprised that the existing non-responsive search bar  hasn't been replaced with [react-native-material-design-searchbar](https://github.com/ananddayalan/react-native-material-design-searchbar).  It would be quick to adapt the props to be backwards compatible.

**Comment by iRoachie** [comment]
We already have a working implementation of the material design searchbar that we released in 1.0.0-beta2. 

You can use it by doing `SearchBar platform="android" />` 

https://react-native-training.github.io/react-native-elements/docs/searchbar.html#platform-specific-searchbar

**Comment by xavier-villelegier** [comment]
@peacechen We've already released Android and iOS SearchBars ([doc here](https://react-native-training.github.io/react-native-elements/docs/searchbar.html#platform-specific-searchbar)). The bug mantionned here is about the default searchbar, that has not been refactored to be as flexible as these new SearchBars.

**Comment by peacechen** [comment]
Nice work!  xavier's tip on the labels makes it look like this is still a WIP as opposed to Fixed.

**Comment by xavier-villelegier** [comment]
Yea it's still WIP because the default searchbar (without `platform` props) is the same as it was when you opened the issue, so the bug is still there. It has to be refactored to be responsive like these new platform specific searchbars 👍

**Comment by iRoachie** [comment]
Closing this as resolved. Should be fixed as the default searchbar now uses the same helpers as the other search bars
