### ISSUE TITLE
Header component height issue in android

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [react-native-training/react-native-elements#813]
Hi I was trying to use the Header component in my app, the header component was working as expected in iOS but in Android I am getting status bar height along with the header component. Is there anyway to remove the status bar height from Android.

Here is the code snippet I have used:

```
<Header
            centerComponent={<Text>Title</Text>}
          rightComponent={
            <Image source={require('../../assets/images/navbar-logout.png')} />
          }
        />
```
Here is the result I am getting in Android and iOS: 

<img width="640" alt="screen shot 2018-01-10 at 8 25 41 pm" src="https://user-images.githubusercontent.com/16349497/34778843-7ec8f062-f644-11e7-8348-a8e4145f0172.png">

Versions:
react-native-elements: ^0.18.5
react: 16.0.0
react-native: 0.51.0

**Comment by iRoachie** [comment]
The height of the status bar is set as a fixed 70 units https://github.com/react-native-training/react-native-elements/blob/4f8225d91bd5917c88b3e70e27a991b12ad4dd1d/src/header/Header.js#L101

On iOS the statusBar overlaps the content, while on android it does not. An easy fix would be to set height for android to `70  - 24` in which 24 is the height of the status bar on android.

A quick workaround in your case would be to change the height of the StatusBar.

```jsx
 outerContainerStyles={{height: Platform.OS === 'ios' ? 70 :  70 - 24}}
```

That way it'll be 70 on iOS as expected and 56 on android

**Comment by jeffreyrajanofficial** [comment]
Awesome thanks @iRoachie that fixed the issue :)

**Comment by iRoachie** [comment]
Proper fix made in https://github.com/react-native-training/react-native-elements/pull/944. Should be available in 1.0.0-beta3

**Comment by iRoachie** [comment]
Live in [1.0.0-beta3](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta3). It should now apply the platform styles by default.

**Comment by akashdathan** [comment]
Still facing this issue

**Comment by akashdathan** [comment]
<img width="301" alt="screenshot 2018-12-18 at 5 20 06 pm" src="https://user-images.githubusercontent.com/19945027/50144074-387f1980-02e9-11e9-9f43-60dc5681bc52.png">

**Comment by iRoachie** [comment]
Fixed on next @akashdathan https://github.com/react-native-training/react-native-elements/commit/de522f1e01393ca75629eb2a69d41e05354c5306

**Comment by KPS250** [comment]
This worked for me:
containerStyle={{height: Platform.OS === 'ios' ? 70 :  70 - 24}}

**Comment by Santiago8888** [comment]
For me on Android:

containerStyle={{marginTop: Platform.OS === 'ios' ? 0 : - 30}}

Was a slight improvement of the previous answer.

**Comment by iRoachie** [comment]
You can try version 1.0.0 right now. It's live.

**Comment by jeffaknine** [comment]
Still the same issue in version 1.0.0. @iRoachie 's fix worked for me

**Comment by dcefram** [comment]
It seems like this is a regression issue? Looks like #1221 broke it based on the diff. I just read the thread in #1105, and it seems like the "hack" used before caused the Header to overlap with the statusbar. 

I also noticed in the screenshots that they were using Expo, wherein I also initially had no problems with the Header in Expo, not until I played around with app.js before publishing the app to Expo. I mean, before modifying app.js and publishing to expo, the app would always overlap with the statusbar, so the default Header's height is just right.

**Comment by iRoachie** [comment]
Can we work on compiling a list of use cases here? So we can test against?

**Comment by Tubek** [comment]
I've just checked this issue on v1.1.0 and it's still an issue.

**Comment by Biplovkumar** [comment]
Same here.

**Comment by Monte9** [comment]
@iRoachie should be reopen?

**Comment by bishnudev** [comment]
same issue. "react-native-elements": "^1.1.0",

Any work around? Solutions posted above didn't work for me.

**Comment by skleeschulte** [comment]
For me `<Header containerStyle={{marginTop: Platform.OS === 'ios' ? 0 : - 24}} ... />` works for version 1.1.0.

**Comment by lFaustus** [comment]
this is what is did for the latest version
`import { StatusBar } from 'react-native';`
`<Header
              containerStyle={{
                marginTop: ((StatusBar.currentHeight || 0) * -1)
              }}
               />
`

**Comment by afandiyusuf** [comment]
got this issue, @lFaustus 's fix work for me. i am using `"react-native-elements": "^1.1.0"`

**Comment by fredsvanelli** [comment]
I'm using "react-native-elements": "^1.2.0" and this bug still there.

@skleeschulte solution worked for me.
